sudo: required
services:
  - docker

before_install:
  - docker build -t atindocker/docker-react -f Dockerfile.dev .
  
script:
   #docker run atindocker/docker-react npm run test -- --coverage
  - docker run atindocker/docker-react

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-314201289163"
  bucket_path: "docker-react"